* +- Keyconfig Documentation
#+begin_html
<p>
<kbd>C</kbd> = <kbd>Ctrl</kbd>; <kbd>M</kbd> = <kbd>Alt</kbd>; <kbd>S</kbd> = <kbd>Shift</kbd>
</p>
#+end_html

Generally follows what you would expect from Maya. Emacs keybindings in the text editor.

Things added by addons are indicated by /italics and an asterisk*/.

-----
=3D View > 3D View (Global)=
| Navigation                              |                          |
|-----------------------------------------+--------------------------|
| Rotate view                             | ~M-<LeftMouse>~            |
| Move view                               | ~M-<MiddleMouse>~          |
| Zoom view                               | ~M-<RightMouse>~           |
| Centre view to cursor                   | ~C-<numpad .>~             |
| Fly navigation                          | ~S-f~                      |
| View all                                | ~a~                        |
| Focus on selected                       | ~f~                        |
| Front view                              | ~<numpad 1>~               |
| Back view                               | ~C-<numpad 1>~             |
| Left view                               | ~<numpad 3>~               |
| Right view                              | ~C-<numpad 3>~             |
| Top view                                | ~<numpad 7>~               |
| Bottom view                             | ~C-<numpad 7>~             |
| Camera view                             | ~<numpad 0>~               |
| Toggle perspective/ortho                | ~M-1~ or ~<numpad-5>~        |
| /Pie menu views*/                         | ~M-`~                      |
| Align view to active front/back/left... | Shift + any of the views |
| Align camera to view                    | ~C-M-<numpad 0>~           |
| Toggle lock camera to view              | ~S-c~                      |

| Shading                      |     |
|------------------------------+-----|
| Wireframe                    |   4 |
| /Toggle wire*/                 | M-4 |
| Toggle textured/solid        |   5 |
| Toggle show backface culling | M-5 |
| Textured                     |   6 |
| Rendered                     |   7 |

| Selection                  |                    |
|----------------------------+--------------------|
| Select                     | ~<LeftMouse>~        |
| Deselect                   | ~C-<LeftMouse>~      |
| Toggle selected/deselected | ~S-<LeftMouse>~      |
| Border select              | ~<LeftMouse>~ drag   |
| Lasso select               | ~<MiddleMouse>~ drag |
| Circle select              | ~S-q~                |

| Snapping                   |           |
|----------------------------+-----------|
| Snap call menu             | ~C-S-s~     |
| Toggle use snap            | ~S-<tab>~   |
|                            | hold ~Ctrl~ |
| Snap to smaller increments | hold ~C-S~  |
| /Snap pie menu*/             | ~C-S-<tab>~ |

| Misc                 |                   |
|----------------------+-------------------|
| /MultiEdit enter*/     | ~<f8>~              |
| /MultiEdit exit*/      | ~M-<f8>~            |
| /Enhanced Set Cursor*/ | ~<mouse5>~ or ~<f10>~ |

| Transformations                    |                                            |
|------------------------------------+--------------------------------------------|
| Manipulators                       | ~q~, ~w~, ~e~, ~r~                                 |
| Precise translate/rotate/scale     | ~C-S~ with ~w~, ~e~, ~r~                           |
| Quick translate                    | drag ~<MiddleMouse>~                         |
| Quick rotate/scale                 | press ~e~, ~r~ with ~<MiddleMouse>~, then let go |
|                                    | of key and keep dragging ~<MiddleMouse>~     |
| Mirror                             | ~C-m~                                        |
| Clear translation, rotation, scale | ~M-w~, ~M-e~, ~M-r~                              |
| Clear origin                       | ~M-o~                                        |
| Set origin                         | ~C-S-M-o~                                    |
| Apply call menu                    | ~C-M-a~                                      |
| Toggle proportional editing        | ~o~                                          |

Right click to cancel operations.

-----
=3D View > Object Mode=
| Object Mode                           |       |
|---------------------------------------+-------|
| Clear restrict view (show everything) | ~C-S-h~ |
| Set restrict view (hide selected)     | ~C-h~   |
| Set restrict view (hide unselected)   | ~M-h~   |
| Join objects (merge objects)          | ~C-j~   |
| Duplicate objects                     | ~C-d~   |
| Duplicate linked                      | ~M-d~   |
| Call menu: Convert to                 | ~M-c~   |

| Grouping                          |         |
|-----------------------------------+---------|
| Select grouped                    | ~S-g~     |
| Create new group                  | ~C-g~     |
| Remove from group                 | ~C-M-g~   |
| Add selected to active group      | ~C-S-g~   |
| Remove selected from active group | ~S-M-g~   |
| Remove from all groups            | ~C-S-M-g~ |

| Misc                           |         |
|--------------------------------+---------|
| Add call menu                  | ~S-a~     |
| Make single user call menu     | ~u~       |
| Make links call menu           | ~C-l~     |
| Toggle subdivisions (modifier) | ~1~, ~2~, ~3~ |

-----
=3D View > Mesh=
| Edit Mode                      |                                         |
|--------------------------------+-----------------------------------------|
| /f2*/                            | ~M-f~                                     |
| Extrude                        | ~M-x~                                     |
| Duplicate or extrude to cursor | ~C-<MiddleMouse>~                         |
| Merge                          | ~M-m~                                     |
| Knife topology tool            | ~K-<LeftMouse>~                           |
|                                | press c to constrain to a straight line |
| Face, edge, vertex call menus  | ~C-f~, ~C-e~, ~C-v~                           |
| Specials call menu             | ~C-<RightMouse>~                          |
| Select mode pie menu           | ~<RightMouse>~                            |

-----
=Window=
| Window              |               |
|---------------------+---------------|
| Search menu         | ~C-<space>~     |
| Duplicate window    | ~C-M-w~         |
| Reload startup file | ~C-n~           |
| Save startup file   | ~C-u~           |
| Open recent         | ~C-S-o~         |
| Open file           | ~C-o~ or ~<f1>~   |
| Save file           | ~C-s~           |
| Save as             | ~C-M-s~ or ~<f2>~ |

-----
=Screen=
| Screen                                |                      |
|---------------------------------------+----------------------|
| Show user preferences                 | ~C-M-u~                |
| Next / previous layout                | ~C-<left>~ / ~C-<right>~ |
| /Layout search*/                        | ~M-<f1>~               |
| Toggle quad view                      | ~<space>~              |
| Toggle sync side views (in quad view) | ~C-S-<space>~          |
| Toggle console                        | ~M-<f2>~               |
| Toggle Header                         | ~M-<f9>~               |
| Render                                | ~<f12>~                |
| Render animation                      | ~C-<f12>~              |
| Toggle render view                    | ~<f11>~                |

| History           |       |
|-------------------+-------|
| Repeat last       | ~g~     |
| Undo              | ~C-z~   |
| Redo              | ~C-S-z~ |
| Show undo history | ~C-M-z~ |

-----

=Text=
| Text Editor              |                     |
|--------------------------+---------------------|
| ← →                      | ~C-f~, ~C-b~, or arrows |
| ↑ ↓                      | ~C-p~, ~C-n~, or arrows |
| Home / end               | Normal or ~C-a~ / ~C-e~ |
| Pg up / down             | Normal or ~C-v~ / ~M-v~ |
| end of buffer            | ~S-M->~               |
| start of buffer          | ~S-M-<~               |
| Select line              | ~C-S-l~               |
| Control size of text     | ~C-<mousewheel>~      |
| Run script               | ~M-p~                 |
| /Run script in pyconsole*/ | ~S-M-p~               |
| /Editor switch buffer*/    | ~M-x~                 |
| Jump                     | ~C-j~                 |
| Find                     | ~C-S-M-f~             |
| Find next                | ~C-s~                 |
| Replace                  | ~C-r~                 |
| Autocomplete             | ~C-<space>~           |
| Cut (kill)               | ~C-w~                 |
| Copy                     | ~M-w~                 |
| Paste (yank)             | ~C-y~                 |
| Save                     | ~M-s~                 |
| Save as                  | ~C-S-M-s~             |

** Bound addons
Sadly a lot of addons bind things for you which interferes with the keyconfig, so I have to unbind them manually and save user settings. If you know of a better way to do it please let me know.
*** Included with blender
- UI Pie Menu Official (unbind the bindings it adds on ~Tab~ and ~Q~: =3D View > Object Non-modal=)
- Extra Objects
- [[https://sites.google.com/site/bartiuscrouch/scripts/f2][f2]] (unbind the binding it adds: =3D View > Mesh > Make Edge/Face= that it binds to ~F~)
*** 3rd party
- [[https://github.com/dairin0d/enhanced-3d-cursor][Enhanced 3D Cursor]] by dairin0d (unbind action mouse)
- [[http://blenderartists.org/forum/showthread.php?352527-Mesh-select-mode-pie-menu][Select Mode Pie Menu]] by Stan Pancakes
- [[https://github.com/antoni4040/MultiEdit-Addon][MultiEdit]]
- [[https://blenderartists.org/forum/showthread.php?331613-ADDON-Wireframe-on-shaded][Wireframe on Shaded Switch]] by stanley82
- [[./../../addons][p-layout-search]]
- [[./../../addons][script-console-output]]
- [[./../../addons][editor-switch-buffer]]
